"""
config.py — Central configuration for the crystal 3D reconstruction pipeline.

Edit the values in this file to match your setup. All other modules read
from here, so this is the only file you need to change between runs.
"""

import os

# ---------------------------------------------------------------------------
# Image acquisition settings
# ---------------------------------------------------------------------------

# Full camera resolution in pixels [width, height]
CAMERA_RESOLUTION = [5328, 4608]

# Scale factor applied to images before processing.
# 1/8 = 12.5% of full resolution (fast, good for testing)
# 1/4 = 25% of full resolution (slower, more detail)
# 1/2 = 50% of full resolution (slow, high detail)
IMAGE_SCALE_FACTOR = 1 / 8

# Degrees between each captured image (1 = 360 images per full rotation)
CAPTURE_STEP_DEGREES = 1

# ---------------------------------------------------------------------------
# Reconstruction settings
# ---------------------------------------------------------------------------

# Resolution of the Z-axis in the 3D voxel block (in pixels before scaling).
# Lower = finer detail but much slower. 5 is a good starting point.
Z_AXIS_STEP_SIZE = 5

# Degrees between reconstruction samples.
# 5 = use every 5th image (fast); 1 = use all 360 images (slow, most accurate)
RECONSTRUCTION_ANGLE_STEP = 5

# ---------------------------------------------------------------------------
# SAM (Segment Anything Model) settings
# ---------------------------------------------------------------------------

# Path to the SAM model checkpoint file.
# Place the .pth file in the notebooks/ folder or update this path.
# Download from: https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth
SAM_CHECKPOINT = os.path.join("notebooks", "sam_vit_b_01ec64.pth")

# SAM model type — must match the checkpoint file.
# Options: "vit_b" (fast), "vit_l" (better), "vit_h" (best)
SAM_MODEL_TYPE = "vit_b"

# SAM bounding box as fractions of image width/height [x1, x2, y1, y2].
# Defines the region SAM searches for the crystal.
# Adjust if the crystal is not centred or is being clipped.
SAM_BBOX = [0.20, 0.80, 0.20, 0.85]

# ---------------------------------------------------------------------------
# Calibration settings
# ---------------------------------------------------------------------------

# Path to the camera calibration pickle file (generated by camera_capture.py).
CALIBRATION_FILE = os.path.join("notebooks", "cal_images2",
                                "Camera_Calibration_0.125.pickle")

# Manual scale correction factor. This was empirically derived by comparing
# the reconstruction output to a 3D-printed reference model.
# A value of 1.0 means no correction. Recalibrate if output dimensions are off.
SCALE_CORRECTION = 0.88

# ---------------------------------------------------------------------------
# Output settings
# ---------------------------------------------------------------------------

# Directory where output files (.asc, .ply) are written.
OUTPUT_DIR = "output"

# ---------------------------------------------------------------------------
# Hardware settings (only used by capture.py on the lab machine)
# ---------------------------------------------------------------------------

# Zaber stage velocity in degrees per second
ZABER_VELOCITY = 5.0

# GenICam CTI file path for the Allied Vision camera
# Update this to match your machine's SDK installation path
CAMERA_CTI_PATH = "C:/Program Files/Allied Vision/Vimba X/api/bin/VimbaC.cti"

# Camera model identifier
CAMERA_MODEL = "1800 U-2460m"

# Camera exposure time in microseconds
CAMERA_EXPOSURE_US = 5000.0

# Camera gain in dB
CAMERA_GAIN_DB = 48.0
