"""
config.py — Central configuration for the crystal 3D reconstruction pipeline.

Edit the values in this file to match your setup. All other modules read
from here, so this is the only file you need to change between runs.

NOTE ON UNITS:
  - All pixel dimensions are at the SCALED resolution (after IMAGE_SCALE_FACTOR
    is applied), not the raw camera resolution.
  - Z_AXIS_STEP_SIZE is in scaled pixels. If you change IMAGE_SCALE_FACTOR,
    reconsider Z_AXIS_STEP_SIZE accordingly.
"""

import os

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# Root directory for image datasets (relative to the project root).
# Image folders are expected to live inside this directory.
DATA_DIR = "notebooks"

# Directory where output files (.asc, .ply) are written.
OUTPUT_DIR = "output"

# ---------------------------------------------------------------------------
# Image acquisition settings
# ---------------------------------------------------------------------------

# Full camera resolution in pixels [width, height].
# This is the native sensor resolution before any scaling is applied.
CAMERA_RESOLUTION = [5328, 4608]

# Scale factor applied to images before processing.
# This affects both memory usage and reconstruction detail.
#   1/8  = 12.5% of full resolution — fast, good for testing and initial runs
#   1/4  = 25%  of full resolution — slower, noticeably more detail
#   1/2  = 50%  of full resolution — slow, high detail (requires significant RAM)
# NOTE: If you change this, also reconsider Z_AXIS_STEP_SIZE below.
IMAGE_SCALE_FACTOR = 1 / 8

# Degrees between each captured image.
# 1 = one image per degree = 360 images per full rotation (recommended).
CAPTURE_STEP_DEGREES = 1

# Total rotation in degrees. Almost always 360.
TOTAL_ROTATION_DEGREES = 360

# ---------------------------------------------------------------------------
# Reconstruction settings
# ---------------------------------------------------------------------------

# Resolution of the Z-axis in the 3D voxel block (in scaled pixels).
# Lower = finer detail but significantly slower and more memory.
# Recommended starting values by scale factor:
#   IMAGE_SCALE_FACTOR = 1/8  → Z_AXIS_STEP_SIZE = 5
#   IMAGE_SCALE_FACTOR = 1/4  → Z_AXIS_STEP_SIZE = 3
#   IMAGE_SCALE_FACTOR = 1/2  → Z_AXIS_STEP_SIZE = 2
Z_AXIS_STEP_SIZE = 5

# Degrees between reconstruction samples.
# 5 = use every 5th image (fast, good for testing)
# 1 = use all 360 images (slow, most accurate)
RECONSTRUCTION_ANGLE_STEP = 5

# Minimum contour area in pixels (at scaled resolution).
# Contours smaller than this are treated as noise and ignored.
# Increase if the segmentation is picking up reflections or background artefacts.
MIN_CONTOUR_AREA = 500

# ---------------------------------------------------------------------------
# SAM (Segment Anything Model) settings
# ---------------------------------------------------------------------------

# Path to the SAM model checkpoint file.
# Place the .pth file in the notebooks/ folder or update this path.
# Download ViT-B (recommended, 375 MB):
#   wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth
# Download ViT-L (better accuracy, 1.2 GB):
#   wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth
SAM_CHECKPOINT = os.path.join(DATA_DIR, "sam_vit_b_01ec64.pth")

# SAM model type — must match the checkpoint file.
# Options: "vit_b" (fast, 375 MB), "vit_l" (better, 1.2 GB), "vit_h" (best, 2.4 GB)
SAM_MODEL_TYPE = "vit_b"

# SAM bounding box as fractions of image [x_left, x_right, y_top, y_bottom].
# Defines the region SAM searches for the crystal.
# Tuning guide:
#   - If the crystal is being clipped at the edges, widen x or y range.
#   - If background is included in the mask, tighten the range.
#   - If the crystal is off-centre, shift x_left/x_right accordingly.
SAM_BBOX = [0.20, 0.80, 0.20, 0.85]

# ---------------------------------------------------------------------------
# Calibration settings
# ---------------------------------------------------------------------------

# Path to the camera calibration pickle file.
# Generated by running: python capture.py --calibrate
CALIBRATION_FILE = os.path.join(DATA_DIR, "cal_images2",
                                "Camera_Calibration_0.125.pickle")

# Manual scale correction factor applied on top of the calibration.
# This was empirically derived by comparing reconstruction output to a
# 3D-printed reference model of known dimensions.
#
# WARNING: This value is specific to the original camera, lens, and working
# distance used during calibration. If any of these change, this factor
# MUST be re-derived by:
#   1. Printing or measuring an object of known dimensions
#   2. Reconstructing it
#   3. Measuring the output and computing: correction = known_size / measured_size
#
# Set to 1.0 to disable the correction entirely.
SCALE_CORRECTION = 0.88

# ---------------------------------------------------------------------------
# Growth monitoring schedule settings
# ---------------------------------------------------------------------------

# Phase 1: frequent captures during the first 24 hours (crystal nucleation / early growth)
PHASE1_HOURS = 24

# Phase 2: moderate captures for the next 6 days (steady growth)
PHASE2_HOURS = 144  # 6 days

# Capture intervals (minutes) for each phase.
# These are the defaults; override with --phase1-mins / --phase2-mins / --phase3-mins.
INTERVAL_PHASE1_MINS = 15   # Every 15 minutes for day 1
INTERVAL_PHASE2_MINS = 30   # Every 30 minutes for days 2–7
INTERVAL_PHASE3_MINS = 60   # Every 60 minutes after day 7

# Minimum allowed interval (minutes) — adaptive tightening will not go below this.
INTERVAL_MIN_MINS = 5

# Adaptive scheduling thresholds.
# If the measured growth rate exceeds ADAPTIVE_FAST_THRESHOLD_MM_HR, the
# interval is halved (down to INTERVAL_MIN_MINS). If it falls below
# ADAPTIVE_SLOW_THRESHOLD_MM_HR, the interval is doubled (up to INTERVAL_PHASE3_MINS).
ADAPTIVE_FAST_THRESHOLD_MM_HR = 0.5   # mm/hr — tighten interval above this
ADAPTIVE_SLOW_THRESHOLD_MM_HR = 0.01  # mm/hr — relax interval below this

# ---------------------------------------------------------------------------
# Facet detection settings
# ---------------------------------------------------------------------------

# Maximum number of crystal facets to detect per run.
MAX_FACETS = 12

# Minimum fraction of the remaining point cloud that must be explained by a
# RANSAC plane for it to be accepted as a real facet.
# Lower = more sensitive (may pick up noise); higher = only prominent facets.
MIN_FACET_INLIER_FRACTION = 0.03

# RANSAC inlier distance threshold in millimetres (or pixel units if --no-scale).
# Points within this distance of the fitted plane are counted as inliers.
# Increase if facets are being missed; decrease if spurious planes are detected.
FACET_DISTANCE_THRESHOLD = 1.5

# ---------------------------------------------------------------------------
# Hardware settings (only used by capture.py on the lab machine)
# ---------------------------------------------------------------------------

# GenICam CTI file path for the Allied Vision camera.
# This is machine-specific and must point to your local Vimba SDK installation.
# If None, capture.py will search common installation paths automatically,
# or prompt you to select from discovered cameras at runtime.
#
# Common paths:
#   Windows: "C:/Program Files/Allied Vision/Vimba X/api/bin/VimbaC.cti"
#   Linux:   "/opt/VimbaX/api/lib/libVimbaC.so"
CAMERA_CTI_PATH = None  # Set to None to auto-discover, or provide a path

# Camera exposure time in microseconds.
CAMERA_EXPOSURE_US = 5000.0

# Camera gain in dB.
CAMERA_GAIN_DB = 48.0

# Number of frames to discard after ia.start() before saving any images.
# Allied Vision cameras often produce 1-2 dark frames immediately after
# streaming starts while the sensor stabilises. Set to 0 to disable.
CAMERA_WARMUP_FRAMES = 3

# Zaber stage serial port.
# Set to None to auto-detect, or specify explicitly e.g. "COM3" or "/dev/ttyUSB0".
ZABER_PORT = None

# Zaber stage velocity in degrees per second.
ZABER_VELOCITY = 5.0

# ---------------------------------------------------------------------------
# Local machine overrides (never committed to git)
# ---------------------------------------------------------------------------
# If a local_settings.py file exists in the project root, its values override
# the defaults above. Use this for machine-specific paths (CTI file, COM port)
# without ever touching this file or risking accidental commits.
#
# To create your local settings:
#   Windows:   copy local_settings.example.py local_settings.py
#   Mac/Linux: cp local_settings.example.py local_settings.py
#
_project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import sys as _sys
if _project_root not in _sys.path:
    _sys.path.insert(0, _project_root)
try:
    from local_settings import *  # noqa: F401, F403
except ImportError:
    pass  # No local_settings.py — using defaults above
